name: CI (4.x)
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  CI-4_x-Java_8:
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: 8
  CI-4_x-Java_17:
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: 17
